title: "Powerview"
remote_theme: fabric-io-rodrigues/just-the-docs
color_scheme: custom

#force text + logo
psr_model: "Power View"
logo: assets/images/psr_logo.png

#adding zoom in images
zoom_img_enabled: true
zoom_img: 
  backgroud: "rgba(0, 0, 0, .5)"
  
#dark/light mode
change_color_enabled: true

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"
