title: "Powerview"
remote_theme: fabric-io-rodrigues/just-the-docs
logo: https://www.psr-inc.com/wp-content/themes/psrNew/favicon.png
color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 PSR."
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
